apiVersion: v2
name: hello
version: 1.0.0
# dependencies:
#   - name: cert-manager
#     version: v1.17.1
#     repository: https://charts.jetstack.io
#   - name: trivy-operator
#     version: 0.24.1
#     repository: https://aquasecurity.github.io/helm-charts
