apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: argocd-backend
spec:
  provider:
    vault:
      server: "http://vault.vault.svc.cluster.local:8200"
      path: "argocd-creds"
      version: "v2"
      auth:
        tokenSecretRef:
          name: "vault-token"
          key: "token"
#         kubernetes:
#           mountPath: "vcluster-1"
#           role: "external-secrets"