---
suite: dummy
suiteVaultUrl: "test.net"
env: "Dev"
envType: "dev"
# serviceAccount:
#   name: "external-secrets"
    # annotations:
    #   azure.workload.identity/tenant-id: f9adec1d-13d3-4ce4-bbd5-10d747afb500
    # labels:
    #   azure.workload.identity/use: "true"

suiteExternalSecrets: {}

###### Trivy Operator #######
